// this file is generated by command.
package utility

import (
    "time"
)

const TzTextAsiaTokyo = "Asia/Tokyo"

type TimeHelper struct {
    tzLocationAsiaTokyo *time.Location
}

var sInsTimeHelper *TimeHelper

func (ins *TimeHelper) NowInAsiaTokyo() (ret time.Time, retErr error) {
    if ins.tzLocationAsiaTokyo == nil {
        if tempTz, loadErr := time.LoadLocation(TzTextAsiaTokyo); loadErr == nil {
            ins.tzLocationAsiaTokyo = tempTz
        } else {
            retErr = loadErr
        }
    }

    if ins.tzLocationAsiaTokyo != nil {
        ret = time.Now().In(ins.tzLocationAsiaTokyo)
    }

    return
}

func NowInAsiaTokyo() (ret time.Time, retErr error) {
    if sInsTimeHelper == nil {
        sInsTimeHelper = &TimeHelper{}
    }

    return sInsTimeHelper.NowInAsiaTokyo()
}

func (ins *TimeHelper) NowInJST() (time.Time, error) {
    return ins.NowInAsiaTokyo()
}

func NowInJST() (ret time.Time, retErr error) {
    if sInsTimeHelper == nil {
        sInsTimeHelper = &TimeHelper{}
    }

    return sInsTimeHelper.NowInJST()
}

func (ins *TimeHelper) NowInUTC() (ret time.Time, retErr error) {
     ret = time.Now().UTC()
    

    return
}

func NowInUTC() (ret time.Time, retErr error) {
    if sInsTimeHelper == nil {
        sInsTimeHelper = &TimeHelper{}
    }

    return sInsTimeHelper.NowInUTC()
}

