// this file is generated by command.
package utility

import (
	"time"
)

const TzTextAsiaTokyo = "Asia/Tokyo"

type TimeHelper struct {
	tzLocationAsiaTokyo *time.Location
}

func (ins *TimeHelper) NowInUTC() (ret time.Time, retErr error) {
	ret = time.Now().UTC()

	return
}

func (ins *TimeHelper) NowInAsiaTokyo() (ret time.Time, retErr error) {
	if ins.tzLocationAsiaTokyo == nil {
		if tempTz, loadErr := time.LoadLocation(TzTextAsiaTokyo); loadErr == nil {
			ins.tzLocationAsiaTokyo = tempTz
		} else {
			retErr = loadErr
		}
	}

	if ins.tzLocationAsiaTokyo != nil {
		ret = time.Now().In(ins.tzLocationAsiaTokyo)
	}

	return
}

func (ins *TimeHelper) NowInJST() (time.Time, error) {
	return ins.NowInAsiaTokyo()
}
