{{define "go_output"}}// this file is generated by command.
package {{.Package}}

import (
    "fmt"
    "strings"
    "time"
)

{{createTimezoneText}}

type {{.Structure}} struct {
{{createStructureFields}}
    tzTextNowMap map[string](func()(time.Time, error))
}

var sIns{{.Structure}} *{{.Structure}}

{{createStructureMethods}}
{{createIsSupportTimezone}}
{{createNowWithTztext}}{{end}}