{{define "go_output"}}// this file is generated by command.
package {{.Package}}

import (
    "time"
)

{{createTimezoneText}}

type {{.Structure}} struct {
{{createStructureFields}}
}

var sIns{{.Structure}} *{{.Structure}}

{{createStructureMethods}}{{end}}